### ISSUE TITLE
Invalid Version 1.21

### ISSUE THREAD

**Issue by PillBoxUnderScore** [datatags/MobChipLite#1]
### Bug Type

Console Errors

### MobChip Version

1.10.4

### Server Version

Paper 1.21

### Description

I'm receiving an error on when attempting to access an entity's brain, or really any functionality of the MobChip API. I suspect this is just an incompatibility oversight or something of the sorts. I believe I read that version 1.10.4 support 1.21 but if that's incorrect I apologize ahead of time!

Error:

```java
[17:40:03 WARN]: [ServerCore] Task #20 for ServerCore v1.0 generated an exception
java.lang.AssertionError: Invalid Version: 1.21
        at ServerCore-1.0-jar-with-dependencies.jar/me.gamercoder215.mobchip.abstraction.ChipUtil.bukkitToCraftBukkit(ChipUtil.java:195) ~[ServerCore-1.0-jar-with-dependencies.jar:?]
        at ServerCore-1.0-jar-with-dependencies.jar/me.gamercoder215.mobchip.abstraction.ChipUtil.getServerVersion(ChipUtil.java:204) ~[ServerCore-1.0-jar-with-dependencies.jar:?]
        at ServerCore-1.0-jar-with-dependencies.jar/me.gamercoder215.mobchip.abstraction.ChipUtil.getWrapper(ChipUtil.java:209) ~[ServerCore-1.0-jar-with-dependencies.jar:?]
        at ServerCore-1.0-jar-with-dependencies.jar/me.gamercoder215.mobchip.bukkit.BukkitBrain.<clinit>(BukkitBrain.java:45) ~[ServerCore-1.0-jar-with-dependencies.jar:?]
        at ServerCore-1.0-jar-with-dependencies.jar/me.pillbox.systems.Imps.setImpRestriction(Imps.java:102) ~[ServerCore-1.0-jar-with-dependencies.jar:?]
        at ServerCore-1.0-jar-with-dependencies.jar/me.pillbox.systems.Imps.customImpFactory(Imps.java:90) ~[ServerCore-1.0-jar-with-dependencies.jar:?]
        at ServerCore-1.0-jar-with-dependencies.jar/me.pillbox.runnables.MonumentRunnable$1.run(MonumentRunnable.java:93) ~[ServerCore-1.0-jar-with-dependencies.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.21.jar:1.21-25-19105a9]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.21.jar:1.21-25-19105a9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1168) ~[paper-1.21.jar:1.21-25-19105a9]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-25-19105a9]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Expected Behavior

1.21 Compatibility

### Actual Behavior

Soft-Erroring on startup and hard erroring when attempting any other API access

### Additional Information

I've updated my Paper to the latest development build to ensure the incompatibility exists.

**Comment by datatags** [comment]
Hello, I'm currently on vacation and won't have time to look at it until July. My own project UltraCosmetics is also using 1.10.4 though and I've heard reports it's working on 1.21, so maybe try running the "clean" task on your project, and then building it with the gradle flag `--refresh-dependencies` or the maven equivalent(?) `-U`, whichever build system you're using.

**Comment by PillBoxUnderScore** [comment]
Hello! Don't worry about this while you are on vacation, my server is still pre-release so no issue.

I've spent the last 2 hours doing just about everything I could think of to get this to work
1. Followed your instructions (Maven)
2. Updated my IDE to it's latest version
3. Updated Maven to its latest version


The only oddity I've discovered is when changing the version to 1.10.2 or 1.10.3 and I go to "Dependency Hierarchy" I see a list of all supported versions as seen here
![1 10 3](https://github.com/datatags/MobChipLite/assets/39451966/4c10e30a-4e52-4711-a801-3ec6589a1486)


However when I then switch to 1.10.4 this is the new "Dependency Hierarchy"
![1 10 4](https://github.com/datatags/MobChipLite/assets/39451966/dd12915f-8618-4d0d-b48d-f58518a2e5c0)

I am new to Maven so I'm unsure if any of this is relevant or if this is something you switched in version 1.10.4.
As stated above no rush and have a nice vacation!

**Comment by datatags** [comment]
Seems like Jitpack had a hiccup and didn't actually include the latest commit in the 1.10.4 release, so I've published 1.10.5 to resolve this. Thanks for your patience!

**Comment by PillBoxUnderScore** [comment]
My IDE is now hanging on 
"Download sources and javadoc: mobchip-bukkit: https://jitpack.io/com/github/datatags/MobChipLite/mobchip-bukkit/1.10.5/mobchip-bukkit-1.10.5-sources.jar" when attempting to update the version in the pom.

**Comment by datatags** [comment]
Hmm, not sure why Jitpack is doing that, seems like it happens when accessing any file that doesn't exist. I may just have to move to CodeMC like MobChip was using before

**Comment by PillBoxUnderScore** [comment]
After working on other parts of my project I revisited this issue and I'm happy to report it's been resolved! Not sure if it was something on your end or my maven dependencies being weird but nonetheless I've tested all my methods from 1.10.3 and they're working perfect on 1.21 on 1.10.5!

Sorry for the re-open and thank you again!
