### ISSUE TITLE
Still getting version related error using 1.10.6 on 1.21.3

### ISSUE THREAD

**Issue by Capri205** [datatags/MobChipLite#3]
### Bug Type

Console Errors

### MobChip Version

1.10.6

### Server Version

paper 1.21.3

### Description

Hi. Not sure if the 1.21.3 compatibility is still being worked on, but I get this error when compiling a plugin using 1.10.6 and running on paper 1.21.3:

java.lang.ExceptionInInitializerError: null
        at LobbyProtect.jar/lobbyprotect.MobChecker.setHomeBound(MobChecker.java:173) ~[LobbyProtect.jar:?]
        at LobbyProtect.jar/lobbyprotect.MobChecker.run(MobChecker.java:129) ~[LobbyProtect.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[paper-1.21.3.jar:1.21.
3-13-42a1901]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1801) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1662) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1328) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Invalid Version: 1_21_R2 (Could not load me.gamercoder215.mobchip.abstraction.v1_21_
R2.ChipUtil1_21_R2)
        at LobbyProtect.jar/me.gamercoder215.mobchip.abstraction.ChipUtil.getWrapper(ChipUtil.java:226) ~[LobbyProtect.jar:?]
        at LobbyProtect.jar/me.gamercoder215.mobchip.bukkit.BukkitBrain.<clinit>(BukkitBrain.java:45) ~[LobbyProtect.jar:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: me.gamercoder215.mobchip.abstraction.v1_21_R2.ChipUtil1_21_R2
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:
?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?
]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy
.java:68) ~[reflection-rewriter-runtime-0.0.3.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[paper-1.21.3.jar:1.21.3-13-42a19
01]
        at LobbyProtect.jar/me.gamercoder215.mobchip.abstraction.ChipUtil.getWrapper(ChipUtil.java:220) ~[LobbyProtect.jar:?]
        at LobbyProtect.jar/me.gamercoder215.mobchip.bukkit.BukkitBrain.<clinit>(BukkitBrain.java:45) ~[LobbyProtect.jar:?]
        ... 9 more

This is different to the previous "Invalid Version" error when compiling with 1.10.5 and running on 1.21.3.

Thanks for keeping this up to date.

### Expected Behavior

Work with 1.21.3, especially setHomeBound.

### Actual Behavior

Getting IlllefalStateException Invalid Version 1_21_R2 (Could not load me.gamercoder215.mobchip.abstraction.v1_21_
R2.ChipUtil1_21_R2)

**Comment by datatags** [comment]
Thanks, I was having a hard time getting my test plugin to run so I thought I'd come back to it later, but I forgot I already tagged it as a new version 🙃 I'll fix this shortly!

**Comment by datatags** [comment]
I've verified 1.10.7 works properly, thanks for your patience!
